version: '3.9'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ../backend/pong/
    ports:
      - "8000:8000"
    volumes:
      - ../backend/pong/:/code
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY}
      METAMASK_PRIVATE_KEY: ${METAMASK_PRIVATE_KEY}

  frontend:
    build: ../frontend-react/
    ports:
      - "3000:3000"
    volumes:
      - ../frontend-react/:/app
      - /app/node_modules
    depends_on:
    - db
    environment:
      - NODE_ENV=development

  nginx:
    build: "../nginx/"
    ports:
      - "443:443"
    volumes:
      - /Users/androsov/Documents/42School/ft_transcendence/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/androsov/Documents/42School/ft_transcendence/nginx/entrypoint.sh:/entrypoint.sh
    depends_on:
      - frontend
    # entrypoint: ["/entrypoint.sh"]

volumes:
  postgres_data:
  
