version: '3.9'

services:
  db:
    image: postgres:13
    container_name: ft_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ft_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    web:
      build: ./src/pong/
      ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
