version: '3.9'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ../backend/pong/
    ports:
      - "8000:8000"
    volumes:
      - ../backend/pong/:/code
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY}
      METAMASK_PRIVATE_KEY: ${METAMASK_PRIVATE_KEY}
      CLIENT_ID_42: ${CLIENT_ID_42}
      CLIENT_SECRET_42: ${CLIENT_SECRET_42}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_VERIFY_SERVICE_SID: ${TWILIO_VERIFY_SERVICE_SID}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

  frontend:
    build: ../frontend-react/
    volumes:
      - ../frontend-react/:/app
      - /app/node_modules
    depends_on:
    - db
    environment:
      NODE_ENV: development
      REACT_APP_TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      REACT_APP_TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      REACT_APP_TWILIO_VERIFY_SERVICE_SID: ${TWILIO_VERIFY_SERVICE_SID}

  # frontend-js:
  #   build: ../frontend-js/
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ../frontend-js/:/app
  #   depends_on:
  #     - db
  #   environment:
  #     NODE_ENV: development

  nginx:
    build: "../nginx/"
    ports:
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/entrypoint.sh:/entrypoint.sh
      - ./localhost+1.pem:/etc/ssl/certs/cert.pem
      - ./localhost+1-key.pem:/etc/ssl/private/key.pem
    depends_on:
      - frontend

volumes:
  postgres_data:
  
